spring:
  application:
    name: User Service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak.baseUrl}/protocol/openid-connect/certs
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER}
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update


server:
  port: 8082
  servlet:
    contextPath: /user-service


keycloak:
  realm: library
  serverUrl: http://keycloak:8080
  baseUrl: ${keycloak.serverUrl}/realms/${keycloak.realm}
  adminApiPath: ${keycloak.serverUrl}/admin/realms
  client-id: user-service
  client-secret: ${USER_SERVICE_CLIENT_SECRET:''}
  tokenUri: ${keycloak.baseUrl}/protocol/openid-connect/token
  users:
    pageSize: 100

user-service:
  initial-load:
    enabled: true
